name: 🔁 Update Quote

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '31 18 * * *'  # Runs daily at 12:01 AM IST (Indian time)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update Quote
        run: node update-quote.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Commit and push changes
        run: |
          git config --global user.name 'suryaaswaththan'
          git config --global user.email 'suryaaswathan@gmail.com'

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          # Ensure we are on main branch
          git checkout main
          
          # Stage and commit changes if any
          git add README.md
          git diff --cached --quiet || git commit --author="suryaaswaththan <suryaaswathan@gmail.com>" -m "🔁 Update README with daily quote"
          
          # Push changes
          git push origin main

